package:
  name: apache2
  version: 2.4.58
  epoch: 0
  description: A high performance Unix-based HTTP server
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - apr-util-dev
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - libapr-dev
      - libxml2-dev
      - lua5.3-dev
      - nghttp2-dev
      - openssl-dev
      - pcre2-dev
      - sed
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: fa16d72a078210a54c47dd5bef2f8b9b8a01d94909a51453956b3ec6442ea4c5
      uri: https://dlcdn.apache.org/httpd/httpd-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: apache2-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - apache2
    description: apache2 dev

  - name: apache2-doc
    pipeline:
      - uses: split/manpages
    description: apache2 manpage

update:
  enabled: true
  release-monitor:
    identifier: 1335
