package:
  name: dotnet-9
  version: 9.0.0
  epoch: 0
  description: ".NET SDK"
  copyright:
    - license: MIT
  resources:
    cpu: 2
    memory: 32Gi
  dependencies:
    runtime:
      - icu

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-15
      - clang-15-default
      - cmake
      - curl
      - glibc-locale-en
      - icu-dev
      - krb5-dev
      - libunwind-dev
      - llvm-18
      - llvm-18-dev
      - llvm-cmake-18
      - lttng-ust-dev
      - ncurses-dev
      - openssl-dev
      - python3
      - samurai
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dotnet/dotnet
      tag: v${{package.version}}
      expected-commit: a2bc464e40415d625118f38fbb0556d1803783ff
      destination: /home/build/src

  - working-directory: /home/build/src
    pipeline:
      - runs: |
          ./build.sh --clean-while-building \
            -- \
            /v:n \
            /p:ContinueOnPrebuiltBaselineError=true \
            /p:MinimalConsoleLogOutput=false \
            /p:SkipPortableRuntimeBuild=true \
            /p:BuildWithOnlineSources=false
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/share/dotnet
          mkdir -p "${{targets.destdir}}"/usr/bin
      - assertions:
          required-steps: 1
        pipeline:
          - if: ${{build.arch}} == 'aarch64'
            runs: |
              tar zxf artifacts/arm64/Release/dotnet-sdk-*.tar.gz -C "${{targets.destdir}}"/usr/share/dotnet
          - if: ${{build.arch}} == 'x86_64'
            runs: |
              tar zxf artifacts/x64/Release/dotnet-sdk-*.tar.gz -C "${{targets.destdir}}"/usr/share/dotnet
      - runs: |
          ln -s /usr/share/dotnet/dotnet "${{targets.destdir}}"/usr/bin/dotnet

  - uses: strip

subpackages:
  - name: ${{package.name}}-runtime
    description: "The .NET Core Runtime, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet/shared
          mv "${{targets.destdir}}"/usr/share/dotnet/shared/Microsoft.NETCore.App "${{targets.subpkgdir}}"/usr/share/dotnet/shared/
    dependencies:
      runtime:
        - ${{package.name}}

  - name: ${{package.name}}-runtime-default
    dependencies:
      runtime:
        - ${{package.name}}-runtime
      provides:
        - dotnet-runtime=9

  - name: aspnet-9-runtime
    description: "The ASP.NET Core Runtime, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet/shared
          mv "${{targets.destdir}}"/usr/share/dotnet/shared/Microsoft.AspNetCore.App "${{targets.subpkgdir}}"/usr/share/dotnet/shared/
    dependencies:
      runtime:
        - ${{package.name}}-runtime

  - name: aspnet-9-runtime-default
    dependencies:
      runtime:
        - aspnet-9-runtime
      provides:
        - aspnet-runtime=9

  - name: ${{package.name}}-targeting-pack
    description: "The .NET Core targeting pack, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet/packs
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/NETStandard.Library.* "${{targets.subpkgdir}}"/usr/share/dotnet/packs/
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/Microsoft.NETCore.App.* "${{targets.subpkgdir}}"/usr/share/dotnet/packs/

  - name: aspnet-9-targeting-pack
    description: "The ASP.NET targeting pack, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet/packs
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/Microsoft.AspNetCore.App.* "${{targets.subpkgdir}}"/usr/share/dotnet/packs/
    dependencies:
      runtime:
        - ${{package.name}}-targeting-pack

  - name: ${{package.name}}-sdk
    description: "The .NET Core SDK, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet

          for i in sdk sdk-manifests templates; do
            mv "${{targets.destdir}}"/usr/share/dotnet/$i "${{targets.subpkgdir}}"/usr/share/dotnet/
          done
    dependencies:
      runtime:
        - ${{package.name}}-runtime
        - aspnet-9-runtime
        - ${{package.name}}-targeting-pack
        - aspnet-9-targeting-pack

  - name: ${{package.name}}-sdk-default
    dependencies:
      runtime:
        - ${{package.name}}-sdk
        - ${{package.name}}-runtime-default
        - aspnet-9-runtime-default
      provides:
        - dotnet-sdk=9

update:
  enabled: true
  github:
    identifier: dotnet/dotnet
    strip-prefix: v
    use-tag: true
    tag-filter: "v9"

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-sdk
  pipeline:
    - name: Basic .NET command test
      runs: |
        dotnet --info
    - name: Compile and run a simple .NET application
      runs: |
        cat <<'EOF' > HelloWorld.cs
        using System;

        class Program
        {
            static void Main()
            {
                Console.WriteLine("Hello, World!");
            }
        }
        EOF
        dotnet new console -o HelloWorldApp --force
        mv HelloWorld.cs HelloWorldApp/Program.cs
        dotnet run --project HelloWorldApp
    - name: Compile and run a .NET application with arguments
      runs: |
        cat <<'EOF' > ArgumentEcho.cs
        using System;

        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Arguments: " + String.Join(", ", args));
            }
        }
        EOF
        dotnet new console -o ArgumentEchoApp --force
        mv ArgumentEcho.cs ArgumentEchoApp/Program.cs
        dotnet run --project ArgumentEchoApp -- arg1 arg2 arg3
